### ISSUE TITLE
Consider sending a PR to open-tamil for Morphological analyzer class

### ISSUE THREAD

**Issue by arcturusannamalai** [Ananthakr/WSD-Tamil#1]
Hello Ananthakr,
Would you be interested to send a pull request to open-tamil package ?
We are developing a spell checker module and we can use your work on morphological analyzer along with Damodaran's stemmer.

Ofcourse some class redesign would be required.
Best,
-Muthu

**Comment by Ananthakr** [comment]
Sure. Can your explain your need? I worked on Word Sense Disambiguation in Tamil. You can contact me via [**ananthakumar.akr@gmail.com** ](mailto:ananthakumar.akr@gmail.com)
